### ISSUE TITLE
NoSuchElementException when parsing parameters

### ISSUE THREAD

**Issue by Nikos410** [DACH-Discord/de-DiscordBot#20]
```
Exception(most recent call first)

java.util.NoSuchElementException: null
    at java.util.LinkedList.removeLast(LinkedList.java:283)
    at de.nikos410.discordBot.DiscordBot.parseParameters(DiscordBot.java:513)
    at de.nikos410.discordBot.DiscordBot.handleMessage(DiscordBot.java:403)
    at de.nikos410.discordBot.DiscordBot.onMessageReceived(DiscordBot.java:308)
    at sx.blah.discord.api.events.EventDispatcher$MethodEventHandler.handle(EventDispatcher.java:680)
    at sx.blah.discord.api.events.EventDispatcher.lambda$null$17(EventDispatcher.java:610)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Nikos410** [comment]
Fixed in 80b2cca
